### ISSUE TITLE
4.4.1.1 breaks OPeNDAP on windows and Python 2.7/3.4

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/libnetcdf-feedstock#10]
With 4.4.1.1, I'm having trouble with netCDF accessing OPeNDAP servers; I get the following error:
```
OSError: NetCDF: Invalid argument
```
I should note that this only happens on AppVeyor, like: https://ci.appveyor.com/project/Unidata/unidata-python-workshop/build/1.0.201/job/jtxca676p2svxgxh

I can reproduce locally on a windows 7 64 vm with Python 3.4; does not happen with Python 3.5

**Comment by ocefpaf** [comment]
I had that issue before the update to 4.4.1.1.

 See ttps://github.com/ioos/notebooks_demos/issues/129

Not sure what is going on but some endpoints work fine others return the `OSError` :unamused:

**Comment by ocefpaf** [comment]
I can confirm that pinning to `4.4.0` fixes the problem. Not sure if that is related to `netcdf` or the packaging in `conda-forge`.

**Comment by rsignell-usgs** [comment]
I just built the IOOS3 environment, and this is failing on Windows:
```
import netCDF4
print(netCDF4.__version__)
url = 'http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ghcncams/air.mon.mean.nc'
nc = netCDF4.Dataset(url)
```
giving:
```
1.2.6

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-04f7b265af90> in <module>()
      2 print(netCDF4.__version__)
      3 url = 'http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ghcncams/air.mon.mean.nc'
----> 4 nc = netCDF4.Dataset(url)

netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__ (netCDF4\_netCDF4.c:13973)()

OSError: NetCDF: I/O failure
```
It works okay on Windows with my IOOS2 environment with older netCDF4 v1.2.4.

**Comment by ocefpaf** [comment]
I am not sure that is a problem with packaging. I believe it it is a bug in `libnetcdf` or `netCDF4`.

What is the `libnetcdf` version? Try force installing `4.4.0`...

**Comment by rsignell-usgs** [comment]
Here's what my IOOS3 Python 3 env looks like for netcdf:
```
(ioos3) C:\Users\rsignell\Documents\GitHub>conda list netcdf
# packages in environment at C:\Users\rsignell\AppData\Local\Continuum\Miniconda
3\envs\ioos3:
#
h5netcdf                  0.3.1                    py35_0    conda-forge
libnetcdf                 4.4.0                    vc14_2  [vc14]  conda-forge
netcdf4                   1.2.6               np111py35_0    conda-forge
```

**Comment by ocefpaf** [comment]
I will try to debug this but some URLs are OK for me when I downgraded from 4.4.1.1 to 4.4.0...

**Comment by ocefpaf** [comment]
This was fixed upstream (https://github.com/Unidata/netcdf-c/pull/366) so we need to wait for a new release (or patch or versoin).
