### ISSUE TITLE
hdf4 support missing on windows

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/libnetcdf-feedstock#11]
Although hdf4 is a general build time dependency (in meta.yaml) it isn't picked up on windows.
According to [this latest log](https://ci.appveyor.com/project/conda-forge/libnetcdf-feedstock/build/1.0.32/job/13d0hskwgoq3gb2k) it is not searched for in the compiler setup and it is reported as "no" in the following build support section.

I would make a PR to fix this, if I knew where and what to look for. 

@ocefpaf Any idea?

XRef: https://github.com/wradlib/wradlib/issues/126

**Comment by ocefpaf** [comment]
Indeed I can see it in line 553

https://ci.appveyor.com/project/conda-forge/libnetcdf-feedstock/build/1.0.32/job/13d0hskwgoq3gb2k#L553

We probably need something like https://github.com/conda-forge/libnetcdf-feedstock/blob/master/recipe/build.sh#L23 in the `bld.bat` but I am not sure if we will need anything else.

@gillins do you have any advice?

**Comment by gillins** [comment]
Hmmm `bld.bat` already seems to have that line - https://github.com/conda-forge/libnetcdf-feedstock/blob/master/recipe/bld.bat#L8

It seems that it is trying to pull in `hdf5` instead (https://ci.appveyor.com/project/conda-forge/libnetcdf-feedstock/build/1.0.32/job/13d0hskwgoq3gb2k#L339 and https://ci.appveyor.com/project/conda-forge/libnetcdf-feedstock/build/1.0.32/job/13d0hskwgoq3gb2k#L524). Very strange.

I'll have a look on my VM and report back.

**Comment by ocefpaf** [comment]
Sam, I cannot look at the logs (only on my phone now) but I added that line
in my last PR.

**Comment by gillins** [comment]
Yes I see your last PR seems to have fixed this (log here https://ci.appveyor.com/project/conda-forge/libnetcdf-feedstock/build/1.0.35/job/6xfffwhk8ksv247r#L378, and can also confirm ok on my VM). Can this be closed? :smile:

**Comment by kmuehlbauer** [comment]
@gillins @ocefpaf Greatly appreciate your looking into this promptly. Thanks for this overnight fixing :-)
