### ISSUE TITLE
zarr enabled?

### ISSUE THREAD

**Issue by rsignell-usgs** [conda-forge/libnetcdf-feedstock#117]
Is zarr enabled on the 4.8.0 build?  
I searched zarr and didn't find it, so I thought perhaps not?
"NCZarr support is enabled if the –enable-nczarr option is used with './configure'."
from
https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/nczarr_head.html

**Comment by rsignell-usgs** [comment]
The CMAKE info is here: 
```
https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/nczarr_head.html#nczarr_cmake
```

**Comment by kmuehlbauer** [comment]
@rsignell-usgs Correct, it's not activated yet. Thanks for the links.

I'll be able to have a look next week. But good chance someone will beat me.

**Comment by ocefpaf** [comment]
> I'll be able to have a look next week. But good chance someone will beat me.

Working on it today... PR soon.

**Comment by benbovy** [comment]
I guess that it is enabled now from #118?

**Comment by ocefpaf** [comment]
Yep. We forgot to close this one. Thanks @benbovy!

**Comment by benbovy** [comment]
@ocefpaf Thanks!

Do you know if, after installing both `netcdf-c` and `netcdf-fortran` from conda-forge, writing nczarr datasets in Fortran will just work?

This is my understanding after reading https://github.com/Unidata/netcdf-fortran/issues/209#issuecomment-832014966 and assuming that the [netcdf-fortran](https://github.com/conda-forge/netcdf-fortran-feedstock) conda package is dynamically linked against this one, but I'm not a netcdf expert so I might miss something.

**Comment by ocefpaf** [comment]
We did not test but, in theory, it should work. Please let us know what you find out.

**Comment by benbovy** [comment]
I've just tried and yes it seems to work well!  (at least with the file mode)
