### ISSUE TITLE
static libraries included

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/libnetcdf-feedstock#134]
I was auditing this recipe and noticed that static libraries are included.

Is any maintainer actively using them? Or do we think it would be safe to simply remove the static libraries from the recipe.

It seems to have been built this way for a long time.

**Comment by xylar** [comment]
@hmaarrfk, this is a great discussion to be had.  There are enough different packages that use `libnetcdf` that it's almost inevitable that some might be using static libraries.  I'm not aware of any off the top of my head, though.  @ocefpaf, how about you?

**Comment by ocefpaf** [comment]
To be honest I do not recall the libs that use the static library. The best course of action would be to do a multiple outputs and create a libnetcdf-static.

**Comment by xylar** [comment]
Ooh, I like that idea.  That way, we could quickly find out which packages need `libnetcdf-static` but we would have a fix that didn't break them for very long.  @hmaarrfk, do you have the time or interest to put in a PR for that purpose?  If not, it might not happen all that soon.

**Comment by hmaarrfk** [comment]
Is there a way to get the package name from the build script?

**Comment by xylar** [comment]
`$PKG_NAME`: https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-set-during-the-build-process

**Comment by xylar** [comment]
Once this is done, we should do the same for `netcdf-fortran`.

**Comment by dopplershift** [comment]
We stopped building the static library with 4.9.0 (#140). Can this be closed?
