### ISSUE TITLE
Incorrect regex in OSX build

### ISSUE THREAD

**Issue by xylar** [conda-forge/libnetcdf-feedstock#170]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As stated in https://github.com/conda-forge/gdal-feedstock/pull/741#issuecomment-1478814528,

> Regex at https://github.com/conda-forge/libnetcdf-feedstock/pull/169 seems wrong

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by xylar** [comment]
@ihnorton, as the author of that PR, could you help us sort this out?

**Comment by xylar** [comment]
I'm not very expert in regex but a bit of googling suggests that `[dylib|tbd]` should instead be `(dylib|tbd)`.

**Comment by rouault** [comment]
fix proposed in https://github.com/conda-forge/libnetcdf-feedstock/pull/171
