### ISSUE TITLE
cmake imported target might be broken

### ISSUE THREAD

**Issue by alexander-buerger-met-no** [conda-forge/libnetcdf-feedstock#173]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have the impression that the latest libnetcdf package on conda-forge causes problems when using libnetcdf as a cmake imported target. The cmake imported target somehow causes the fimex build to expect libz.so in the fimex build directory, and libz.so is obviously not there:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=676229&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0

(See line 499 in the build output.) This problem has not been present in previous libnetcdf versions, and is not present when using libnetcdf via pkg-config instead of as a cmake imported target.

### Installed packages

```shell
conda build
```

### Environment info

```shell
conda version : 23.1.0
    conda-build version : 3.24.0
         python version : 3.8.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.8.16 Linux/4.15.0-206-generic ubuntu/18.04.6 glibc/2.27
             netrc file : None
           offline mode : False
```

**Comment by alexander-buerger-met-no** [comment]
I add a minimalistic copy of the messages from the fimex conda-forge build here as I do not know how long these are kept on azure:
```
…
-- Found netCDF via cmake imported
…
make[2]: *** No rule to make target '/home/conda/feedstock_root/build_artifacts/fimex_1679303126679/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libz.so', needed by 'src/io/netcdf/libfimex-io-netcdf.so.0.0.0'.  Stop.
```

**Comment by alexander-buerger-met-no** [comment]
The build now also fails due with libnetcdf 4.9.1-nompi_hf3f8848_103 with more or less the same error message. It is unclear to me why zlib / `libz.so` is expected to be in the fimex build directory.

**Comment by zklaus** [comment]
I think it is right to expect `libz.so` in the build environment and it does seem like the correct libzlib package gets installed. As such, I suspect this is not a `libnetcdf` problem. I am trying to debug the issue at conda-forge/fimex-feedstock#61, but I'll close this issue here.

Of course, feel free to reopen if you disagree or if new evidence comes to light.

**Comment by alexander-buerger-met-no** [comment]
New attempt to find out what is wrong. First building fimex with `libnetcdf=4.8.1`, which works, then with `libnetcdf==4.9.1`, which not work.

With two conda envs `nc481` and `nc491` containing `libnetcdf==4.8.1` and `libnetcdf==4.9.1`, respectively, the most relevant diff between the cmake files for libnetcdf seems to be for `netCDFTargets.cmake` (stripping the path until `envs`):

```
-  INTERFACE_LINK_LIBRARIES "ENVS/nc481/lib/libmfhdf.so;ENVS/nc481/lib/libdf.so;ENVS/nc481/lib/libhdf5_hl.so;ENVS/nc481/lib/libhdf5.so;m;ENVS/nc481/lib/libcurl.so;ENVS/nc481/lib/libzip.so"
+  INTERFACE_LINK_LIBRARIES "dl;ENVS/nc491/lib/libmfhdf.so;ENVS/nc491/lib/libdf.so;ENVS/nc491/lib/libhdf5_hl.so;ENVS/nc491/lib/libhdf5.so;ENVS/nc491/lib/libcrypto.so;ENVS/nc491/lib/libcurl.so;rt;pthread;ENVS/nc491/lib/libsz.so;ENVS/nc491/lib/libz.so;dl;m;ENVS/nc491/lib/libzip.so;ENVS/nc491/lib/libzstd.so;ENVS/nc491/lib/libbz2.so;ENVS/nc491/lib/libxml2.so"

```

There are many more files in the 4.9.1 version. Some are a bit surprising to see there, for example `dl` and `m` (libdl and libm). Finally, I checked if each of the referred `lib....so` files is present:

```
ls: cannot access 'ENVS/nc491/lib/libz.so': No such file or directory
ENVS/nc491/lib/libbz2.so
ENVS/nc491/lib/libcrypto.so
ENVS/nc491/lib/libcurl.so
ENVS/nc491/lib/libdf.so
ENVS/nc491/lib/libhdf5_hl.so
ENVS/nc491/lib/libhdf5.so
ENVS/nc491/lib/libmfhdf.so
ENVS/nc491/lib/libsz.so
ENVS/nc491/lib/libxml2.so
ENVS/nc491/lib/libzip.so
ENVS/nc491/lib/libzstd.so
```

So the `netCDFTargets.cmake` from 4.9.1 refers to a non-existing file `ENVS/nc491/lib/libz.so`. This file is present in the nc481 environment, coming from the `zlib` package. This package is not installed in the `nc491` environment. Apparently, it is not a dependency that gets installed automatically. In commit 72d9369c1f, `zlib` has been removed from the `run` dependencies. Maybe it should be added again, if the cmake file refers to it?

**Comment by alexander-buerger-met-no** [comment]
The `libz.so` file, which is only needed for compilation, is indeed in the `zlib` package:
https://github.com/conda-forge/zlib-feedstock/blob/main/recipe/meta.yaml#L86

@zklaus I hope you can re-open and solve the issue.

**Comment by alexander-buerger-met-no** [comment]
I agree that it would be better not to add a "runtime" dependency on `zlib` to the `libnetcdf` package and instead get rid of the `.../lib.so` in the cmake targets file.

I suspect that `libz.so` appears there because it is not added as a `PRIVATE` library in [liblib/CMakeLists.txt](https://github.com/Unidata/netcdf-c/blob/main/liblib/CMakeLists.txt#L162) in the netcdf-c cmake files, see [target_link_libraries](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents). Maybe `TLL_LIBS` should be split into `TLL_LIBS` and `TLL_PRIVATE_LIBS`? I expect that it would be fine to link `zlib`  with `PRIVATE` (preferably using the "imported target"). On the other hand, `grep -rn '\<zlib.h\>' *` only finds a single `#include` in [plugins/H5Zdeflate.c](https://github.com/Unidata/netcdf-c/blob/main/plugins/H5Zdeflate.c#L23). Maybe it is sufficient to add `zlib` to the `h5deflate` plugin only?

Changing the netcdf-c cmake build scripts might take some time. Until this is done, it would be nice to have back `zlib` in the conda-forge package as a runtime dependency. Otherwise, the cmake config from that package is not useable.

**Comment by zklaus** [comment]
Fair enough. If it is not too hard to fix, we could also add another patch here that can be upstreamed. After all, we try to be good open source devs and help to scratch the itches we encounter :wink:.

@alexander-buerger-met-no, could you perhaps see if there is an upstream issue or open one that we might reference in the recipe to revisit things when this bug is fixed?

**Comment by alexander-buerger-met-no** [comment]
I submitted a draft PR for netcdf-c: https://github.com/Unidata/netcdf-c/pull/2729.
