### ISSUE TITLE
Test in recipe points to dead URL

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/libnetcdf-feedstock#18]
Data on http://thredds.ucar.edu are constantly rotating, so probably best not to use that as a test. That's currently causing the re-render Pos to fail.

**Comment by ocefpaf** [comment]
Do you have a stable endpoint or should we just remove it?

**Comment by dopplershift** [comment]
You'd have to do one of:

1. Python test script using siphon to resolve the `latest` catalog
2. Use some template magic to point to yesterday's data

Neither of those seem worth it IMO.
