### ISSUE TITLE
Enable quantization by default?

### ISSUE THREAD

**Issue by czender** [conda-forge/libnetcdf-feedstock#190]
### Comment:

AFAICT the netCDF quantization options are not enabled in the conda-forge netCDF library. This is distinct from https://github.com/conda-forge/netcdf4-feedstock/issues/154 because the "new" compressors like Zstandard need plugins, etc, whereas quantization needs no external libraries so it is mysterious to me why it is not enabled by default. From an up-to-date Conda-forge library:

```
zender@login10:~$ which nc-config
/ccs/home/zender/anaconda/bin/nc-config
zender@login10:~$ nc-config --libdir
/ccs/home/zender/anaconda/lib
zender@login10:~$ nc-config --version
netCDF 4.9.2
zender@login10:~$ nc-config --has-quantize
no
zender@login10:~$ 
``` 
I build netCDF often from upstream (Unidata) snapshots and AFAICT the Autotools build machinery requires no specific options to enable quantization. So I suspect that this may be a CMake issue that affects netcdf4-feedstock builds, but not people who build with Autotools. If you are unable to activate quantization with CMake then I will kick this report upstream to Unidata. In any case, it would be great if Conda-forge feedstock folks figured out how to enable quantization by default. Thanks for your efforts!

**Comment by zklaus** [comment]
Hi @czender, I agree entirely that it should be activated. However, I also think it is, since I did some testing on its effects on the compression. Could you try just to use it to double-check whether it is rather a problem in the `nc-config` script (which has given us some headaches in the past)?

**Comment by czender** [comment]
@zklaus You are quite right. I should have been more skeptical of the script. Quantization is active, but the `nc-config` script returns an incorrect value. It appears to be broken in a different way in the current snapshot upstream (Unidata), where I have submitted a bug report. Nothing to be done here in the feedstock.

**Comment by zklaus** [comment]
Sorry about the script trouble. I am not sure this is the case here, but these scripts are notoriously tricky for conda-forge to get right because they translate build environment information into the runtime environment.
