### ISSUE TITLE
Rebuild with new pinnings

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libnetcdf-feedstock#45]
Would be nice to have `libnetcdf` rebuilt with the newest pinnings. Includes a pin for `hdf4`, a newer version of `hdf5`, and different version constraints on `curl`.

**Comment by xylar** [comment]
I believe there have been one or more rebuilds since this issue was created.  Can it be closed?

**Comment by ocefpaf** [comment]
> I believe there have been one or more rebuilds since this issue was created. Can it be closed?

Yep. Old issue. Thanks @xylar!
