### ISSUE TITLE
conda-forge netCDF nc-config --libs produces incorrect results

### ISSUE THREAD

**Issue by czender** [conda-forge/libnetcdf-feedstock#57]
https://github.com/conda-forge/netcdf4-feedstock/issues/59

describes the issue. I'm unsure whether that issue properly belongs to netcdf4-feedstock or libnetcdf-feedstock, because I'm unsure how to tell which package provides a given exectuable, though I suspect that libnetcdf owns/installs `nc-config`. In any case, I would appreciate it if someone could try to reproduce the problem so we know whether it's just me or generic to the package.

**Comment by dopplershift** [comment]
I'm pretty sure here is the proper repo. Not sure what's going on.

**Comment by ocefpaf** [comment]
Just tested with,

```
$ conda create --name TEST libnetcdf
$ conda activate TEST
$ which nc-config

/home/filipe/miniconda3/envs/TEST/bin/nc-config

$ nc-config --libs

-L/home/filipe/miniconda3/envs/TEST//home/filipe/miniconda3/envs/TEST/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl
```

The env prefix, `/home/filipe/miniconda3/envs/TEST/`, is double... Not sure why :-/

@msarahan and @mingwandroid do you know what may be going on here? The same happens with the packages from `defaults` BTW.

**Comment by budall** [comment]
Hi, 
I'm having exactly the same problem on a Ubuntu 18.04 system and need to fix this, but have no idea how.

Note the double '//' in the nc-config --libs return value.

I've tried to uninstall netcdf and reinstall it to no avail -- being a newbie on Linux does not help.

Any clues appreciated....thanks..

**Comment by ocefpaf** [comment]
My only guess is that is an issue with the prefix substitution in conda/conda-build. @msarahan can probably help us narrow this down.

**Comment by budall** [comment]
Ok. I’ve had a couple of makefiles fail now due to lines with “$(shell nc-config –libs)” returning the incorrect string with the partially duplicated location of the libs files (and the double //) in that string.

 

Thanks @msarahan for helping!

 

Brad

**Comment by ocefpaf** [comment]
Maybe @jjhelmus can help shed some light on this issue.

**Comment by jjhelmus** [comment]
The doubled `//` is present in nc-config prior to the prefix substitution so the issue is not with conda-build.  

```
$ cat nc-config | grep libs
libs="-L/home/jhelmus/anaconda3/conda-bld/libnetcdf_1539959611646/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_//home/jhelmus/anaconda3/conda-bld/libnetcdf_1539959611646/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl"
```

**Comment by jjhelmus** [comment]
The [`nc-config.cmake.in`](https://github.com/Unidata/netcdf-c/blob/v4.6.1/nc-config.cmake.in#L14) file assumes that **CMAKE_INSTALL_LIBDIR** is a relative path but `build.sh` [sets this as an absolute path](https://github.com/conda-forge/libnetcdf-feedstock/blob/master/recipe/build.sh#L35).  I will submit a PR with a fix shortly.

**Comment by xylar** [comment]
We're running into issues where the conda-forge version of netCDF4 thinks it doesn't support CDF-5 format.  I suspect that this issue is related to this issue.  If `nc-config` is not giving a valid path, then netCDF4 does not find the include directory it needs during setup:
https://github.com/Unidata/netcdf4-python/blob/master/setup.py#L342-L353

Later on, the setup routine looks in this include path to see if (among other things) CDF-5 support is available:
https://github.com/Unidata/netcdf4-python/blob/master/setup.py#L76-L77

I can post an issue about this elsewhere but wanted to check here first to see if others also think the issues might be related.

cc @czender, @vanroekel

Possibly related to https://github.com/MPAS-Dev/MPAS-Analysis/issues/459

**Comment by ocefpaf** [comment]
> The [`nc-config.cmake.in`](https://github.com/Unidata/netcdf-c/blob/v4.6.1/nc-config.cmake.in#L14) file assumes that **CMAKE_INSTALL_LIBDIR** is a relative path but `build.sh` [sets this as an absolute path](https://github.com/conda-forge/libnetcdf-feedstock/blob/master/recipe/build.sh#L35). I will submit a PR with a fix shortly.

Thanks @jjhelmus!
