### ISSUE TITLE
DAP and curl

### ISSUE THREAD

**Issue by pelson** [conda-forge/libnetcdf-feedstock#6]
Just wanted to let my future self know about a problem I had compiling on an old system (RHEL6) when DAP was enabled:

```
[ 54%] Building C object libdap2/CMakeFiles/dap2.dir/constraints.c.o
In file included from /data/local/itpe/conda_bld/root/libnetcdf_1473686262452/work/netcdf-c-4.4.1/libdap2/constraints.c:7:
/data/local/itpe/conda_bld/root/libnetcdf_1473686262452/work/netcdf-c-4.4.1/libdap2/dceparselex.h:48: error: redefinition of typedef 'DCEparsestate'
/data/local/itpe/conda_bld/root/libnetcdf_1473686262452/work/netcdf-c-4.4.1/libdap2/dceparselex.h:11: note: previous declaration of 'DCEparsestate' was here
```

My working solution was to patch the source as per http://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2016/msg00197.html. Don't know why we didn't need to do that here, but it is now here for posterity should it come up.

Strangely, I also ended up using `export LDFLAGS="-L${PREFIX}/lib -ljpeg -lcrypto"` (the jpeg was for ncgen) and also set `-D CMAKE_PREFIX_PATH=$PREFIX`.

Note, in case that link were to ever disappear, the patch was:

```
--- libdap2/dceparselex.h.orig  2016-09-12 14:21:09.832676026 +0100
+++ libdap2/dceparselex.h   2016-09-12 14:25:32.032368839 +0100
@@ -40,12 +40,12 @@
 } DCElexstate;

 /*! Specifies DCEparsestate. */
-typedef struct DCEparsestate {
+struct DCEparsestate {
     DCEconstraint* constraint;
     char errorbuf[1024];
     int errorcode;
     DCElexstate* lexstate;
-} DCEparsestate;
+};

 /* Define a generic object carrier; this serves
    essentially the same role as the typical bison %union
```

**Comment by ocefpaf** [comment]
I can prepare the patch and bump the build here but shouldn't we see the same failure in `CircleCI`? I just restarted the build and everything worked (just a connection issue with the DAP test but the build is fine.)

**Comment by pelson** [comment]
I just wanted to raise it. Given we didn't need to do it here for CircleCI, I was a little surprised that I needed to change anything. I don't see value in us maintaining things that conda-forge doesn't need here - not least because we can't guarantee it will continue to work going forwards.

**Comment by jakirkham** [comment]
FYI it is a gcc 4.4 issue. If we were still using gcc 4.4, we would probably need the patch. I can't find the bug report for it, but it was fixed in gcc 4.5.

**Comment by xylar** [comment]
Can this issue be closed?

**Comment by ocefpaf** [comment]
It is stale. @pelson if you still need action here please re-open.
