### ISSUE TITLE
libnetcdf 4.6.2 incompatible with Python 2.7 on Windows

### ISSUE THREAD

**Issue by djhoese** [conda-forge/libnetcdf-feedstock#65]
This is related to https://github.com/conda-forge/netcdf4-feedstock/pull/72

I need to rebuild the netcdf4-python library (see PR above) and the build is currently failing on appveyor on a python 2.7 environment. I have a Windows VM that I've now created a python 2.7 environment and tried to force it to install the newest libnetcdf build and it won't let me. Note I also tried installing the new HDF5 which succeeded by downgrading libnetcdf to 4.3.3.1. I then tried updating libnetcdf which tried to downgrade hdf5. My end goal is to have the newest hdf5 (1.10.4) and the newest libnetcdf in a single python 2.7 environment.

```
(appveyor_debug_27) C:\Users\User>conda install "libnetcdf=4.6.2=h396784b_1000" "python=2.7"
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - libnetcdf==4.6.2=h396784b_1000
  - python=2.7
Use "conda info <package>" to see the dependencies for each package.
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
bzip2                     1.0.6             h0c8e037_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cftime                    1.0.2.1         py27hc997a72_1000    conda-forge
curl                      7.62.0            h2f83ebf_1000    conda-forge
hdf4                      4.2.12                    vc9_0  [vc9]  ioos
hdf5                      1.10.4          nompi_hb8085ad_1003    conda-forge
icc_rt                    2017.0.4             h97af966_0
intel-openmp              2019.1                      144
jpeg                      8d                        vc9_0  [vc9]  ioos
krb5                      1.16.2            hb4d044e_1000    conda-forge
libcurl                   7.62.0            h2f83ebf_1000    conda-forge
libnetcdf                 4.3.3.1                   vc9_4
libssh2                   1.8.0                h77a7533_4
mkl                       2018.0.3                      1
mkl_fft                   1.0.10                   py27_0    conda-forge
numpy                     1.15.4           py27hbe4291b_0
numpy-base                1.15.4           py27h2753ae9_0
openssl                   1.0.2p            h0c8e037_1001    conda-forge
pip                       18.1                  py27_1000    conda-forge
python                    2.7.15            h2880e7c_1006    conda-forge
setuptools                40.6.2                   py27_0    conda-forge
tk                        8.6.9             h0c8e037_1000    conda-forge
vc                        9                             0    conda-forge
vs2008_runtime            9.0.30729.6161                0    conda-forge
wheel                     0.32.3                   py27_0    conda-forge
wincertstore              0.2                   py27_1002    conda-forge
zlib                      1.2.11            h3cc03e0_1003    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by kmuehlbauer** [comment]
@djhoese Gnarf, we dropped py27 for windows. Reason was that backpatching was too cumbersome, see https://github.com/conda-forge/libnetcdf-feedstock/pull/61#issuecomment-441321811.

Sorry for the bad news.

**Comment by djhoese** [comment]
Part of me says "awesome!", the other part says 😮 

So as mentioned in the linked issue I'm trying to figure out how to get hdf5, netcdf, and libnetcdf on a Windows Python 2.7 environment. Right now it is telling me that hdf5 and libnetcdf are not compatible. My guess was that a rebuild of libnetcdf was needed to pull in new dependencies that python 2.7 may be used, but now I realize what is happening is `libnetcdf` 4.6.2 is not built for python 2.7 and 4.6.1 is not built with hdf5 1.10.4.

Could we (you?) create a rebuild of libnetcdf 4.6.1 with hdf5 1.10.4?

If not, this means that h5py, netcdf4-python, and gdal will no longer support python 2.7 (without rebuilds of those packages for older versions of libraries). While I personally am fine dropping python 2.7 support, I don't think all users are.

**Comment by kmuehlbauer** [comment]
@djhoese From my perspective it should be possible to create a libnetcd 4.6.1 with hdf5 1.10.4. But my conda skills are not sufficient. So I would suggest to ask @ocefpaf.

**Comment by djhoese** [comment]
Thanks @ocefpaf. I completely understand. Hopefully, with my netcdf PR I can at least get an environment. It doesn't have to be the newest versions, just has to work for another 6-12 months.
