### ISSUE TITLE
Re-add 4.6.3

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/libnetcdf-feedstock#74]
I'm pulled the 4.6.3 packages b/c the `soname` from `libnetcdf.so.13` to `libnetcdf.so.15` and this breaks our stack. I'll update the pinning first and then we can re-add `4.6.3`.

See

https://anaconda.org/conda-forge/libnetcdf/files?version=4.6.3

and 

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/199

Ping @djhoese 

PS: `4.6.3` should actually be `4.7.0`. :-/

**Comment by djhoese** [comment]
I'm a little lost, but I'll just assume you're figuring everything out. Just a concerned/hopeful user 😉

**Comment by ocefpaf** [comment]
> I'm a little lost, but I'll just assume you're figuring everything out. Just a concerned/hopeful user

The TL;DR is:

- `v4.6.3` is working but the `soname` changed from `libnetcdf.so.13` to `libnetcdf.so.15`;
- at the moment we are pinning to `x.x`, which means any ABI breaking change, like the name change above, is expected to happen only when bumping minor version, not micro (`x.x.x`);
- in order to upgrade to `v4.6.3` we need to update our pinning to `v4.6.2` exact and `x.x.x`, so the built packages don't pull `v4.6.3` and break with a missing `libnetcdf.so.13` message.

Then, we can update the pinning to `v4.6.3` and let the new packages for `v4.6.3` "free."

**Comment by beckermr** [comment]
@ocefpaf If this package provides more than the so, we might consider separating the so out to its own build.

**Comment by djhoese** [comment]
Ah thank you for the explanation. So if upstream had named this version `4.7` this wouldn't have been a problem since all packages could have been pinned to that 2-field version number. I don't mind bugging people so... @wardf what standards/conventions does the C NetCDF library follow for choosing its version numbers? The semantic versioning I have the most experience with put larger/breaking features (like those in 4.6.2 or 4.6.3) in a new "minor" or even "major" release (like 4.7). Just curious. Thanks.

**Comment by ocefpaf** [comment]
> @ocefpaf If this package provides more than the so, we might consider separating the so out to its own build.

Yeah. It was already badly named `libnetcdf` when the real name is `netcdf-c`, which is also odd b/c users only care about the "netcdf" name :smile: 

Anyway, we can split it into `netcdf` and `libnetcdf`. But that won't help much here b/c most of the packages downstream would depended on `libnetcdf` and require a rebuild anyway.

**Comment by ocefpaf** [comment]
> Ah thank you for the explanation. So if upstream had named this version `4.7` this wouldn't have been a problem since all packages could have been pinned to that 2-field version number.

Exactly. Or, if we knew that netcdf-c does not follow semver, we had the pin set to micro (`x.x.x`) instead.

> I don't mind bugging people so... @WardF what standards/conventions does the C NetCDF library follow for choosing its version numbers? The semantic versioning I have the most experience with put larger/breaking features (like those in 4.6.2 or 4.6.3) in a new "minor" or even "major" release (like 4.7). Just curious. Thanks.

:+1:

**Comment by beckermr** [comment]
right. as long as we have to rebuild for a new so, we might as well do the split first though

**Comment by ocefpaf** [comment]
> right. as long as we have to rebuild for a new so, we might as well do the split first though

I'll work on that next week, unless someone beats me to it.

**Comment by beckermr** [comment]
ain't gonna be me :)

**Comment by ocefpaf** [comment]
@WardF do you think we can have a `4.7.0` release of those changes instead of `4.6.3`? That would really helps us b/c we would not need to write hacky workarounds to the SEMVER breakage.

**Comment by WardF** [comment]
Sorry for the delayed response all!

@djhoese NetCDF does not historically adhere to a given standard for incrementing, although we adhere (with occasional exceptions) to the semver major.minor.revision numbering system, with bugfix releases typically extending it out to four numbers.  Moving forward, we can stick to the 3-number system.  I'll need to review semver further before saying whether we will adopt the complete methodology.

@ocefpaf The horse is already out of the barn at this point; 4.6.3 was released and announced earlier this month, with tarballs and windows executables available from the Unidata website.  I see the 4.6.3 release on GitHub was still marked as a draft, but there's no way for me to reconcile changing that to 4.7.0 with the announcement and available 4.6.3 sourcecode.  I will try to get a 4.7.0 release out asap, however. We are working to mint a new Fortran release, currently.

**Comment by ocefpaf** [comment]
> @ocefpaf The horse is already out of the barn at this point; 4.6.3 was released and announced earlier this month, with tarballs and windows executables available from the Unidata website. I see the 4.6.3 release on GitHub was still marked as a draft, but there's no way for me to reconcile changing that to 4.7.0 with the announcement and available 4.6.3 sourcecode.

No problem. Thanks for the feedback.

>  I will try to get a 4.7.0 release out asap, however. We are working to mint a new Fortran release, currently.

In that case I believe that we are probably going to skip `4.6.3` and wait for `4.7.0` to avoid major headaches. (Unless there are crucial bugfixes in 4.6.3.)

**Comment by ocefpaf** [comment]
We have a PR for 4.7.0 now in #76. Closing this one.
