### ISSUE TITLE
use ENABLE_SHARED_LIBRARY_VERSION=OFF

### ISSUE THREAD

**Issue by speleo3** [conda-forge/libnetcdf-feedstock#96]
This is related to #74 (`soname` change in 4.6.3) and https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/199

I suggest to add [`-DENABLE_SHARED_LIBRARY_VERSION=OFF`](https://github.com/Unidata/netcdf-c/issues/228) with the next `x.x` version update. The result will be that programs link against `libnetcdf.so` instead of `libnetcdf.so.15`.

NetCDF seems to have [great backwards compatibility](https://abi-laboratory.pro/?view=timeline&l=netcdf) and the `soname` forces unnecessary strict pinning. Conda's default pinning mechanism should typically be sufficient to depend on a compatible version.

**Comment by ocefpaf** [comment]
@isuruf what do you think about this idea?

**Comment by isuruf** [comment]
We shouldn't second guess upstream like that. If they say the soname needs to change, then it should. https://abi-laboratory.pro/index.php?view=timeline&l=netcdf doesn't show 4.7.4 which I guess will show some incompatibilities.

**Comment by ocefpaf** [comment]
It is quite an odd option to have BTW. I'm not confident using it.

**Comment by ocefpaf** [comment]
I'm closing this b/c we are not OK using that option. I believe that our current pinning scheme is robust enough. If you disagree I'd be happy to discuss this further.

**Comment by speleo3** [comment]
Thanks for your time, I respect your decision. We have our own workaround in place to not link against the versioned library name.
